# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: true

notifications:
  email:
    on_success: change
    on_failure: change

r_apt_packages:
  - testthat
  - knitr

r_github_packages:
  - jimhester/covr
##  - nimble-dev/nimble/packages/nimble@devel

before_install:
  - Rscript -e "install.packages('igraph',   repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "library(devtools); install_github('nimble-dev/nimble', ref = 'devel', subdir = 'packages/nimble')"

after_success:
  - Rscript -e 'library(covr); coveralls()'

