# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: true

notifications:
  email:
    on_success: change
    on_failure: change

##r_apt_packages:
##  - testthat
##  - knitr

##r_github_packages:
##  - jimhester/covr
##  - nimble-dev/nimble/packages/nimble@stable

install:
  - Rscript -e "install.packages('knitr',    repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('testthat', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('igraph',   repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('devtools', repos = 'http://cran.us.r-project.org')"
  - Rscript -e "install.packages('covr',     repos = 'http://cran.us.r-project.org')"
  - Rscript -e "library(devtools); install_github('nimble-dev/nimble', ref = 'stable', subdir = 'packages/nimble')"
  - Rscript -e "library(devtools); install_github('danielturek/gpmanagement')"

script:
  - Rscript tests/testthat.R

after_success:
  - Rscript -e 'library(covr); coveralls()'

